name: my_mobility_services
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.20.2
  firebase_core: ^3.15.2
  cloud_firestore: ^5.6.12
  flutter_svg: ^2.2.0
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  firebase_auth: ^5.7.0
  path_drawing: ^1.0.1
  flutter_map: ^6.1.0
  google_maps_flutter: ^2.9.0
  latlong2: ^0.9.0
  http: ^1.1.0
  geolocator: ^11.1.0
  geocoding: ^2.2.2
  permission_handler: ^11.4.0
  glassmorphism: ^3.0.0
  url_launcher: ^6.2.2
  timezone: ^0.9.4
  country_code_picker: ^3.0.0
  flutter_stripe: ^10.2.0
  flutter_local_notifications: ^17.2.4
  audioplayers: ^5.2.1
  firebase_messaging: ^15.2.10
  pdf: ^3.10.7
  printing: ^5.14.2
  path_provider: ^2.1.2
  app_links: ^3.5.1
  onesignal_flutter: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.0

flutter_native_splash:
  color: "#000000"
  image: assets/images/MBG-LogoJauneLime.png
  android: true
  ios: true

  android_12:                   
    color: "#000000"            
    image: assets/images/MBG-LogoJauneLime.png     


flutter:
  uses-material-design: true
  generate: true
  assets :
    - assets/images/MBG-Logo.svg
    - assets/images/Apple_logo_black.svg
    - assets/images/2023_Facebook_icon.svg
    - assets/images/Google__G__logo.svg
    - assets/images/MBG-LogoJauneLime.png
    - assets/sounds/
    - assets/icons/
